// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFZIqqnXAJ5ywcup4GWXiH4hY_wLYVYXc',
    appId: '1:22550268821:web:bd3a63ebe1378560b6049c',
    messagingSenderId: '22550268821',
    projectId: 'jobpostapp-c0d65',
    authDomain: 'jobpostapp-c0d65.firebaseapp.com',
    storageBucket: 'jobpostapp-c0d65.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnVN4ByOWeX8aY4BAIFzcJ0eOv-6PdR_o',
    appId: '1:22550268821:android:3ea2620e5f507b5fb6049c',
    messagingSenderId: '22550268821',
    projectId: 'jobpostapp-c0d65',
    storageBucket: 'jobpostapp-c0d65.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzMrfxTzOFJ0LBnULRUtUSlSzRZwGGYpk',
    appId: '1:22550268821:ios:50daf3e827cfad6eb6049c',
    messagingSenderId: '22550268821',
    projectId: 'jobpostapp-c0d65',
    storageBucket: 'jobpostapp-c0d65.appspot.com',
    iosBundleId: 'com.limon.jobPostApp',
  );
}
